package com.beatblock.ui.panels;

import com.beatblock.BeatBlock;
import com.beatblock.client.BeatBlockClientDriver;
import com.beatblock.engine.AnimationDefinition;
import com.beatblock.engine.StageObject;
import com.beatblock.timeline.Clip;
import com.beatblock.timeline.EventType;
import com.beatblock.timeline.Timeline;
import com.beatblock.timeline.TimelineAnimationActionMode;
import com.beatblock.timeline.TimelineEditor;
import com.beatblock.timeline.TimelineEvent;
import com.beatblock.timeline.Track;
import com.beatblock.timeline.editor.SelectionState;
import com.beatblock.timeline.rendering.TimelineTrackMeta;
import com.beatblock.timeline.rendering.TrackDefinition;
import com.beatblock.timeline.rendering.TrackRegistry;
import com.beatblock.ui.layout.BeatBlockDockSpaceLayoutBuilder;
import imgui.ImGui;
import imgui.flag.ImGuiWindowFlags;
import imgui.type.ImBoolean;
import imgui.type.ImInt;
import imgui.type.ImString;
import net.minecraft.registry.Registries;
import net.minecraft.util.Identifier;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * 右侧事件属性面板。
 */
public class EventPropertiesPanel {

	private static final int WINDOW_FLAGS = ImGuiWindowFlags.NoCollapse;
	private static final int INPUT_BUFFER_SIZE = 128;

	private String boundEventId;
	private final ImString timeBuffer = new ImString(INPUT_BUFFER_SIZE);
	private final ImString durationBuffer = new ImString(INPUT_BUFFER_SIZE);
	private final ImString energyBuffer = new ImString(INPUT_BUFFER_SIZE);
	private final ImString energyThresholdBuffer = new ImString(INPUT_BUFFER_SIZE);
	private final ImString placeBlockBuffer = new ImString(INPUT_BUFFER_SIZE);
	private String validationError;

	private record EventRef(Track track, Clip clip, TimelineEvent event) {}
	private record Option(String id, String label) {}

	public void render(ImBoolean pOpen) {
		if (!pOpen.get()) {
			return;
		}
		if (!ImGui.begin(BeatBlockDockSpaceLayoutBuilder.EVENT_PROPERTIES_WINDOW, pOpen, WINDOW_FLAGS)) {
			ImGui.end();
			return;
		}
		ImGui.text("事件属性");
		ImGui.separator();

		Timeline timeline = BeatBlock.timeline;
		TimelineEditor editor = BeatBlock.timelineEditor;
		if (timeline == null || editor == null) {
			ImGui.textDisabled("时间线未初始化。");
			ImGui.end();
			return;
		}

		EventRef ref = resolveSelectedEventRef(timeline, editor.getSelectionState());
		if (ref == null) {
			boundEventId = null;
			validationError = null;
			ImGui.textWrapped("选中时间线上的事件后，可在此编辑属性。");
			ImGui.end();
			return;
		}

		if (!ref.event().getId().equals(boundEventId)) {
			bindBuffers(ref.event());
		}

		renderEventSummary(ref, timeline);
		ImGui.separator();

		if (ref.event().getType() != EventType.ANIMATION) {
			ImGui.textDisabled("当前仅支持在侧栏编辑动画事件。");
			ImGui.end();
			return;
		}

		boolean trackLocked = isTrackLocked(timeline, editor, ref.track().getId());
		if (trackLocked) {
			ImGui.textDisabled("当前轨道已锁定，属性只读。");
			ImGui.separator();
			ImGui.beginDisabled();
		}

		renderAnimationEditor(ref, timeline);

		if (trackLocked) {
			ImGui.endDisabled();
		}
		ImGui.end();
	}

	private void renderEventSummary(EventRef ref, Timeline timeline) {
		Map<String, Object> params = ref.event().getParameters();
		ImGui.textDisabled("Track");
		ImGui.sameLine();
		ImGui.text(ref.track().getName().isBlank() ? ref.track().getId() : ref.track().getName());
		ImGui.textDisabled("Event ID");
		ImGui.sameLine();
		ImGui.text(ref.event().getId());
		if (Timeline.isBlockAnimationFeatureTrackId(ref.track().getId())) {
			ImGui.textDisabled("Feature Lane");
			ImGui.sameLine();
			ImGui.text(TrackRegistry.localizedName(Timeline.blockAnimationFeatureKeyFromTrackId(ref.track().getId())));
		}
		String sourceFeature = stringParam(params, "sourceFeature");
		if (!sourceFeature.isBlank()) {
			ImGui.textDisabled("Source Feature");
			ImGui.sameLine();
			ImGui.text(TrackRegistry.localizedName(sourceFeature));
		}
		String generatedBy = stringParam(params, "generatedBy");
		if (!generatedBy.isBlank()) {
			ImGui.textDisabled("Generated By");
			ImGui.sameLine();
			ImGui.text(generatedBy);
		}
		ImGui.textDisabled("Action Mode");
		ImGui.sameLine();
		Object actionMode = params.get("actionMode") != null ? params.get("actionMode") : params.get("mode");
		ImGui.text(TimelineAnimationActionMode.fromValue(actionMode).name());
	}

	private void renderAnimationEditor(EventRef ref, Timeline timeline) {
		Map<String, Object> params = ref.event().getParameters();
		List<Option> actionOptions = collectActionOptions();
		List<Option> animationOptions = collectAnimationOptions();
		List<Option> targetOptions = collectTargetOptions();

		ImGui.text("Timing");
		ImGui.setNextItemWidth(-1f);
		ImGui.inputText("开始时间 (s)##eventTime", timeBuffer);
		ImGui.setNextItemWidth(-1f);
		ImGui.inputText("持续时间 (s)##eventDuration", durationBuffer);
		ImGui.setNextItemWidth(-1f);
		ImGui.inputText("能量 (0-1)##eventEnergy", energyBuffer);
		ImGui.setNextItemWidth(-1f);
		ImGui.inputText("能量阈值 (0-1)##eventEnergyThreshold", energyThresholdBuffer);

		String currentAnimationId = stringParam(params, "animationType");
		String currentTargetId = stringParam(params, "targetObject");
		String currentActionMode = stringParam(params, "actionMode", stringParam(params, "mode", TimelineAnimationActionMode.ANIMATE.name()));
		ImInt actionIndex = new ImInt(indexOfOption(actionOptions, currentActionMode));
		ImInt animationIndex = new ImInt(indexOfOption(animationOptions, currentAnimationId));
		ImInt targetIndex = new ImInt(indexOfOption(targetOptions, currentTargetId));
		String[] actionLabels = optionLabels(actionOptions);
		String[] animationLabels = optionLabels(animationOptions);
		String[] targetLabels = optionLabels(targetOptions);

		ImGui.spacing();
		ImGui.text("Binding");
		if (ImGui.combo("动作模式##eventActionMode", actionIndex, actionLabels)) {
			validationError = null;
		}
		if (ImGui.combo("动画模板##eventAnimation", animationIndex, animationLabels)) {
			validationError = null;
		}
		if (ImGui.combo("目标对象##eventTarget", targetIndex, targetLabels)) {
			validationError = null;
		}
		TimelineAnimationActionMode selectedActionMode = TimelineAnimationActionMode.fromValue(actionOptions.get(actionIndex.get()).id());
		if (selectedActionMode == TimelineAnimationActionMode.PLACE) {
			ImGui.setNextItemWidth(-1f);
			ImGui.inputText("放置方块ID##eventPlaceBlock", placeBlockBuffer);
			if (ImGui.isItemHovered()) {
				ImGui.setTooltip("例如: minecraft:diamond_block");
			}
		}

		ImGui.spacing();
		ImGui.text("Metadata");
		ImGui.textDisabled(String.format(Locale.ROOT, "Mapping: %s", stringParam(params, "mappingProfile", "manual")));
		ImGui.textDisabled(String.format(Locale.ROOT, "Source Stem: %s", stringParam(params, "sourceStem", "-")));
		renderRuntimeStatus(ref);

		if (validationError != null && !validationError.isBlank()) {
			ImGui.spacing();
			ImGui.textColored(1f, 0.45f, 0.45f, 1f, validationError);
		}

		ImGui.spacing();
		boolean applied = ImGui.button("应用##eventPropertiesApply", 120f, 0f);
		ImGui.sameLine();
		boolean reset = ImGui.button("重置##eventPropertiesReset", 120f, 0f);

		if (applied) {
			applyAnimationChanges(ref, timeline,
				actionOptions.get(actionIndex.get()).id(),
				animationOptions.get(animationIndex.get()).id(),
				targetOptions.get(targetIndex.get()).id());
		}
		if (reset) {
			bindBuffers(ref.event());
		}
	}

	private void renderRuntimeStatus(EventRef ref) {
		String eventId = ref != null && ref.event() != null ? ref.event().getId() : "";
		if (eventId == null || eventId.isBlank()) return;
		BeatBlockClientDriver.TimelineActionExecutionReport report = BeatBlockClientDriver.getTimelineActionExecutionReport(eventId);
		if (report == null) return;

		long ageMs = Math.max(0L, System.currentTimeMillis() - report.timestampMs());
		ImGui.textDisabled(String.format(Locale.ROOT,
			"Runtime: %s | %s | mutations=%d | %dms ago",
			report.actionMode().name(),
			report.status(),
			report.mutationCount(),
			ageMs));
		if (report.detail() != null && !report.detail().isBlank()) {
			ImGui.textDisabled("detail: " + report.detail());
		}
	}

	private void applyAnimationChanges(EventRef ref, Timeline timeline, String actionMode, String animationId, String targetObjectId) {
		try {
			double newTime = Math.max(0.0, Double.parseDouble(valueOf(timeBuffer).trim()));
			double newDuration = Math.max(0.01, Double.parseDouble(valueOf(durationBuffer).trim()));
			float newEnergy = (float) Math.max(0.0, Math.min(1.0, Double.parseDouble(valueOf(energyBuffer).trim())));
			float newEnergyThreshold = (float) Math.max(0.0, Math.min(1.0, Double.parseDouble(valueOf(energyThresholdBuffer).trim())));
			TimelineAnimationActionMode mode = TimelineAnimationActionMode.fromValue(actionMode);
			if (targetObjectId == null || targetObjectId.isBlank()) {
				validationError = "请先选择目标对象。";
				return;
			}
			if (BeatBlock.blockAnimationEngine == null || BeatBlock.blockAnimationEngine.getStageObjectSystem().get(targetObjectId) == null) {
				validationError = "目标对象不存在，请重新选择。";
				return;
			}
			String placeBlockId = null;
			if (mode == TimelineAnimationActionMode.PLACE) {
				String blockId = valueOf(placeBlockBuffer).trim();
				if (blockId.isEmpty()) {
					blockId = "minecraft:diamond_block";
				}
				Identifier parsed = Identifier.tryParse(blockId);
				if (parsed == null || !Registries.BLOCK.containsId(parsed)) {
					validationError = "方块ID无效，示例: minecraft:diamond_block";
					return;
				}
				placeBlockId = parsed.toString();
			}

			ref.event().setTimeSeconds(newTime);
			ref.event().setParameter("actionMode", mode.name());
			ref.event().setParameter("mode", mode.name());
			ref.event().setParameter("durationSeconds", newDuration);
			ref.event().setParameter("energy", newEnergy);
			ref.event().setParameter("energyThreshold", newEnergyThreshold);
			ref.event().setParameter("animationType", animationId);
			ref.event().setParameter("targetObject", targetObjectId);
			if (mode == TimelineAnimationActionMode.PLACE) {
				ref.event().setParameter("placeBlock", placeBlockId);
			} else {
				ref.event().removeParameter("placeBlock");
				ref.event().removeParameter("placeBlockId");
			}
			ref.clip().setStartTimeSeconds(newTime);
			ref.clip().setEndTimeSeconds(newTime + newDuration);
			timeline.markAnimationEventsDirty(ref.track().getId());
			validationError = null;
			bindBuffers(ref.event());
		} catch (NumberFormatException ex) {
			validationError = "时间、持续时间或能量格式不正确。";
		}
	}

	private void bindBuffers(TimelineEvent event) {
		boundEventId = event.getId();
		Map<String, Object> params = event.getParameters();
		timeBuffer.set(String.format(Locale.ROOT, "%.6f", event.getTimeSeconds()));
		durationBuffer.set(String.format(Locale.ROOT, "%.6f", numericParam(params, "durationSeconds", 0.25)));
		energyBuffer.set(String.format(Locale.ROOT, "%.3f", numericParam(params, "energy", 1.0)));
		energyThresholdBuffer.set(String.format(Locale.ROOT, "%.3f", numericParam(params, "energyThreshold", 0.15)));
		String placeBlock = stringParam(params, "placeBlock", stringParam(params, "placeBlockId", "minecraft:diamond_block"));
		placeBlockBuffer.set(placeBlock);
		validationError = null;
	}

	private EventRef resolveSelectedEventRef(Timeline timeline, SelectionState selectionState) {
		if (timeline == null || selectionState == null || selectionState.getSelectedEvents().isEmpty()) return null;
		List<String> selectedIds = new ArrayList<>(selectionState.getSelectedEvents());
		selectedIds.sort(String::compareTo);
		for (String eventId : selectedIds) {
			for (Track track : timeline.getTracks()) {
				for (Clip clip : track.getClips()) {
					TimelineEvent event = clip.getEvent(eventId);
					if (event != null) return new EventRef(track, clip, event);
				}
			}
		}
		return null;
	}

	private boolean isTrackLocked(Timeline timeline, TimelineEditor editor, String trackId) {
		if (editor == null || trackId == null || trackId.isBlank()) return false;
		int rowIndex = logicalRowForTrackId(timeline, trackId);
		return rowIndex >= 0 && editor.getTrackListState().isLocked(rowIndex);
	}

	private int logicalRowForTrackId(Timeline timeline, String trackId) {
		if (trackId == null || trackId.isBlank()) return -1;
        switch (trackId) {
            case Timeline.TRACK_ID_AUDIO -> {
                return TimelineTrackMeta.ROW_AUDIO_GROUP;
            }
            case Timeline.TRACK_ID_ANIMATION_BLOCK -> {
                return TimelineTrackMeta.ROW_ANIM_BLOCK;
            }
            case Timeline.TRACK_ID_ANIMATION_AUTO -> {
                return TimelineTrackMeta.ROW_ANIM_AUTO;
            }
            case Timeline.TRACK_ID_CAMERA -> {
                return TimelineTrackMeta.ROW_CAMERA;
            }
            case Timeline.TRACK_ID_GLOBAL -> {
                return TimelineTrackMeta.ROW_GLOBAL_EVENT;
            }
        }
        if (timeline != null && Timeline.isBlockAnimationFeatureTrackId(trackId)) {
			List<TrackDefinition> defs = TrackRegistry.buildBlockAnimationControlTracks(timeline);
			for (int i = 0; i < defs.size() && i < TimelineTrackMeta.MAX_ANIMATION_SUB_ROWS; i++) {
				if (trackId.equals(defs.get(i).getKey())) {
					return TimelineTrackMeta.ROW_ANIM_FEATURES_START + i;
				}
			}
		}
		return -1;
	}

	private List<Option> collectAnimationOptions() {
		List<Option> options = new ArrayList<>();
		options.add(new Option("", "未绑定"));
		if (BeatBlock.blockAnimationEngine == null) return options;
		List<AnimationDefinition> defs = new ArrayList<>(BeatBlock.blockAnimationEngine.getAnimationLibrary().getAll().values());
		defs.sort(Comparator.comparing(AnimationDefinition::getName, String.CASE_INSENSITIVE_ORDER));
		for (AnimationDefinition def : defs) {
			options.add(new Option(def.getId(), def.getName() + " [" + def.getId() + "]"));
		}
		return options;
	}

	private List<Option> collectActionOptions() {
		List<Option> options = new ArrayList<>();
		for (TimelineAnimationActionMode mode : TimelineAnimationActionMode.values()) {
			String label = switch (mode) {
				case ANIMATE -> "动画";
				case PLACE -> "放置";
				case CLEAR -> "清除";
				case BUILD -> "建造";
			};
			options.add(new Option(mode.name(), label + " [" + mode.name() + "]"));
		}
		return options;
	}

	private List<Option> collectTargetOptions() {
		List<Option> options = new ArrayList<>();
		options.add(new Option("", "未绑定"));
		if (BeatBlock.blockAnimationEngine == null) return options;
		List<StageObject> objects = new ArrayList<>(BeatBlock.blockAnimationEngine.getStageObjectSystem().getAll());
		objects.sort(Comparator.comparing(StageObject::getName, String.CASE_INSENSITIVE_ORDER));
		for (StageObject object : objects) {
			options.add(new Option(object.getId(), object.getName() + " [" + object.getId() + "]"));
		}
		return options;
	}

	private static int indexOfOption(List<Option> options, String id) {
		for (int i = 0; i < options.size(); i++) {
			if (options.get(i).id().equals(id)) return i;
		}
		return 0;
	}

	private static String[] optionLabels(List<Option> options) {
		String[] labels = new String[options.size()];
		for (int i = 0; i < options.size(); i++) {
			labels[i] = options.get(i).label();
		}
		return labels;
	}

	private static String stringParam(Map<String, Object> params, String key) {
		return stringParam(params, key, "");
	}

	private static String stringParam(Map<String, Object> params, String key, String fallback) {
		Object value = params != null ? params.get(key) : null;
		return value != null ? String.valueOf(value) : fallback;
	}

	private static double numericParam(Map<String, Object> params, String key, double fallback) {
		Object value = params != null ? params.get(key) : null;
		return value instanceof Number ? ((Number) value).doubleValue() : fallback;
	}

	private static String valueOf(ImString text) {
		String value = text != null ? text.get() : null;
		return value != null ? value : "";
	}
}
