package com.beatblock.ui.panels;

import com.beatblock.BeatBlock;
import com.beatblock.engine.AnimationDefinition;
import com.beatblock.engine.StageObject;
import com.beatblock.timeline.Clip;
import com.beatblock.timeline.EventType;
import com.beatblock.timeline.Timeline;
import com.beatblock.timeline.TimelineEditor;
import com.beatblock.timeline.TimelineEvent;
import com.beatblock.timeline.Track;
import com.beatblock.timeline.editor.SelectionState;
import com.beatblock.timeline.rendering.TimelineTrackMeta;
import com.beatblock.timeline.rendering.TrackDefinition;
import com.beatblock.timeline.rendering.TrackRegistry;
import com.beatblock.ui.layout.BeatBlockDockSpaceLayoutBuilder;
import imgui.ImGui;
import imgui.flag.ImGuiWindowFlags;
import imgui.type.ImInt;
import imgui.type.ImString;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * 右侧事件属性面板。
 */
public class EventPropertiesPanel {

	private static final int WINDOW_FLAGS = ImGuiWindowFlags.NoCollapse;
	private static final int INPUT_BUFFER_SIZE = 128;

	private String boundEventId;
	private final ImString timeBuffer = new ImString(INPUT_BUFFER_SIZE);
	private final ImString durationBuffer = new ImString(INPUT_BUFFER_SIZE);
	private final ImString energyBuffer = new ImString(INPUT_BUFFER_SIZE);
	private String validationError;

	private record EventRef(Track track, Clip clip, TimelineEvent event) {}
	private record Option(String id, String label) {}

	public void render() {
		if (!ImGui.begin(BeatBlockDockSpaceLayoutBuilder.EVENT_PROPERTIES_WINDOW, WINDOW_FLAGS)) {
			ImGui.end();
			return;
		}
		ImGui.text("事件属性");
		ImGui.separator();

		Timeline timeline = BeatBlock.timeline;
		TimelineEditor editor = BeatBlock.timelineEditor;
		if (timeline == null || editor == null) {
			ImGui.textDisabled("时间线未初始化。");
			ImGui.end();
			return;
		}

		EventRef ref = resolveSelectedEventRef(timeline, editor.getSelectionState());
		if (ref == null) {
			boundEventId = null;
			validationError = null;
			ImGui.textWrapped("选中时间线上的事件后，可在此编辑属性。");
			ImGui.end();
			return;
		}

		if (!ref.event().getId().equals(boundEventId)) {
			bindBuffers(ref.event());
		}

		renderEventSummary(ref, timeline);
		ImGui.separator();

		if (ref.event().getType() != EventType.ANIMATION) {
			ImGui.textDisabled("当前仅支持在侧栏编辑动画事件。");
			ImGui.end();
			return;
		}

		boolean trackLocked = isTrackLocked(timeline, editor, ref.track().getId());
		if (trackLocked) {
			ImGui.textDisabled("当前轨道已锁定，属性只读。");
			ImGui.separator();
			ImGui.beginDisabled();
		}

		renderAnimationEditor(ref, timeline);

		if (trackLocked) {
			ImGui.endDisabled();
		}
		ImGui.end();
	}

	private void renderEventSummary(EventRef ref, Timeline timeline) {
		Map<String, Object> params = ref.event().getParameters();
		ImGui.textDisabled("Track");
		ImGui.sameLine();
		ImGui.text(ref.track().getName().isBlank() ? ref.track().getId() : ref.track().getName());
		ImGui.textDisabled("Event ID");
		ImGui.sameLine();
		ImGui.text(ref.event().getId());
		if (Timeline.isBlockAnimationFeatureTrackId(ref.track().getId())) {
			ImGui.textDisabled("Feature Lane");
			ImGui.sameLine();
			ImGui.text(TrackRegistry.localizedName(Timeline.blockAnimationFeatureKeyFromTrackId(ref.track().getId())));
		}
		String sourceFeature = stringParam(params, "sourceFeature");
		if (!sourceFeature.isBlank()) {
			ImGui.textDisabled("Source Feature");
			ImGui.sameLine();
			ImGui.text(TrackRegistry.localizedName(sourceFeature));
		}
		String generatedBy = stringParam(params, "generatedBy");
		if (!generatedBy.isBlank()) {
			ImGui.textDisabled("Generated By");
			ImGui.sameLine();
			ImGui.text(generatedBy);
		}
	}

	private void renderAnimationEditor(EventRef ref, Timeline timeline) {
		Map<String, Object> params = ref.event().getParameters();
		List<Option> animationOptions = collectAnimationOptions();
		List<Option> targetOptions = collectTargetOptions();

		ImGui.text("Timing");
		ImGui.setNextItemWidth(-1f);
		ImGui.inputText("开始时间 (s)##eventTime", timeBuffer);
		ImGui.setNextItemWidth(-1f);
		ImGui.inputText("持续时间 (s)##eventDuration", durationBuffer);
		ImGui.setNextItemWidth(-1f);
		ImGui.inputText("能量 (0-1)##eventEnergy", energyBuffer);

		String currentAnimationId = stringParam(params, "animationType");
		String currentTargetId = stringParam(params, "targetObject");
		ImInt animationIndex = new ImInt(indexOfOption(animationOptions, currentAnimationId));
		ImInt targetIndex = new ImInt(indexOfOption(targetOptions, currentTargetId));
		String[] animationLabels = optionLabels(animationOptions);
		String[] targetLabels = optionLabels(targetOptions);

		ImGui.spacing();
		ImGui.text("Binding");
		if (ImGui.combo("动画模板##eventAnimation", animationIndex, animationLabels)) {
			validationError = null;
		}
		if (ImGui.combo("目标对象##eventTarget", targetIndex, targetLabels)) {
			validationError = null;
		}

		ImGui.spacing();
		ImGui.text("Metadata");
		ImGui.textDisabled(String.format(Locale.ROOT, "Mapping: %s", stringParam(params, "mappingProfile", "manual")));
		ImGui.textDisabled(String.format(Locale.ROOT, "Source Stem: %s", stringParam(params, "sourceStem", "-")));

		if (validationError != null && !validationError.isBlank()) {
			ImGui.spacing();
			ImGui.textColored(1f, 0.45f, 0.45f, 1f, validationError);
		}

		ImGui.spacing();
		boolean applied = ImGui.button("应用##eventPropertiesApply", 120f, 0f);
		ImGui.sameLine();
		boolean reset = ImGui.button("重置##eventPropertiesReset", 120f, 0f);

		if (applied) {
			applyAnimationChanges(ref, timeline,
				animationOptions.get(animationIndex.get()).id(),
				targetOptions.get(targetIndex.get()).id());
		}
		if (reset) {
			bindBuffers(ref.event());
		}
	}

	private void applyAnimationChanges(EventRef ref, Timeline timeline, String animationId, String targetObjectId) {
		try {
			double newTime = Math.max(0.0, Double.parseDouble(valueOf(timeBuffer).trim()));
			double newDuration = Math.max(0.01, Double.parseDouble(valueOf(durationBuffer).trim()));
			float newEnergy = (float) Math.max(0.0, Math.min(1.0, Double.parseDouble(valueOf(energyBuffer).trim())));

			ref.event().setTimeSeconds(newTime);
			ref.event().setParameter("durationSeconds", newDuration);
			ref.event().setParameter("energy", newEnergy);
			ref.event().setParameter("animationType", animationId);
			ref.event().setParameter("targetObject", targetObjectId);
			ref.clip().setStartTimeSeconds(newTime);
			ref.clip().setEndTimeSeconds(newTime + newDuration);
			timeline.markAnimationEventsDirty(ref.track().getId());
			validationError = null;
			bindBuffers(ref.event());
		} catch (NumberFormatException ex) {
			validationError = "时间、持续时间或能量格式不正确。";
		}
	}

	private void bindBuffers(TimelineEvent event) {
		boundEventId = event.getId();
		Map<String, Object> params = event.getParameters();
		timeBuffer.set(String.format(Locale.ROOT, "%.6f", event.getTimeSeconds()));
		durationBuffer.set(String.format(Locale.ROOT, "%.6f", numericParam(params, "durationSeconds", 0.25)));
		energyBuffer.set(String.format(Locale.ROOT, "%.3f", numericParam(params, "energy", 1.0)));
		validationError = null;
	}

	private EventRef resolveSelectedEventRef(Timeline timeline, SelectionState selectionState) {
		if (timeline == null || selectionState == null || selectionState.getSelectedEvents().isEmpty()) return null;
		List<String> selectedIds = new ArrayList<>(selectionState.getSelectedEvents());
		selectedIds.sort(String::compareTo);
		for (String eventId : selectedIds) {
			for (Track track : timeline.getTracks()) {
				for (Clip clip : track.getClips()) {
					TimelineEvent event = clip.getEvent(eventId);
					if (event != null) return new EventRef(track, clip, event);
				}
			}
		}
		return null;
	}

	private boolean isTrackLocked(Timeline timeline, TimelineEditor editor, String trackId) {
		if (editor == null || editor.getTrackListState() == null || trackId == null || trackId.isBlank()) return false;
		int rowIndex = logicalRowForTrackId(timeline, trackId);
		return rowIndex >= 0 && editor.getTrackListState().isLocked(rowIndex);
	}

	private int logicalRowForTrackId(Timeline timeline, String trackId) {
		if (trackId == null || trackId.isBlank()) return -1;
		if (Timeline.TRACK_ID_AUDIO.equals(trackId)) return TimelineTrackMeta.ROW_AUDIO_GROUP;
		if (Timeline.TRACK_ID_ANIMATION_BLOCK.equals(trackId)) return TimelineTrackMeta.ROW_ANIM_BLOCK;
		if (Timeline.TRACK_ID_ANIMATION_AUTO.equals(trackId)) return TimelineTrackMeta.ROW_ANIM_AUTO;
		if (Timeline.TRACK_ID_CAMERA.equals(trackId)) return TimelineTrackMeta.ROW_CAMERA;
		if (Timeline.TRACK_ID_GLOBAL.equals(trackId)) return TimelineTrackMeta.ROW_GLOBAL_EVENT;
		if (timeline != null && Timeline.isBlockAnimationFeatureTrackId(trackId)) {
			List<TrackDefinition> defs = TrackRegistry.buildBlockAnimationControlTracks(timeline);
			for (int i = 0; i < defs.size() && i < TimelineTrackMeta.MAX_ANIMATION_SUB_ROWS; i++) {
				if (trackId.equals(defs.get(i).getKey())) {
					return TimelineTrackMeta.ROW_ANIM_FEATURES_START + i;
				}
			}
		}
		return -1;
	}

	private List<Option> collectAnimationOptions() {
		List<Option> options = new ArrayList<>();
		options.add(new Option("", "未绑定"));
		if (BeatBlock.blockAnimationEngine == null) return options;
		List<AnimationDefinition> defs = new ArrayList<>(BeatBlock.blockAnimationEngine.getAnimationLibrary().getAll().values());
		defs.sort(Comparator.comparing(AnimationDefinition::getName, String.CASE_INSENSITIVE_ORDER));
		for (AnimationDefinition def : defs) {
			options.add(new Option(def.getId(), def.getName() + " [" + def.getId() + "]"));
		}
		return options;
	}

	private List<Option> collectTargetOptions() {
		List<Option> options = new ArrayList<>();
		options.add(new Option("", "未绑定"));
		if (BeatBlock.blockAnimationEngine == null) return options;
		List<StageObject> objects = new ArrayList<>(BeatBlock.blockAnimationEngine.getStageObjectSystem().getAll());
		objects.sort(Comparator.comparing(StageObject::getName, String.CASE_INSENSITIVE_ORDER));
		for (StageObject object : objects) {
			options.add(new Option(object.getId(), object.getName() + " [" + object.getId() + "]"));
		}
		return options;
	}

	private static int indexOfOption(List<Option> options, String id) {
		for (int i = 0; i < options.size(); i++) {
			if (options.get(i).id().equals(id)) return i;
		}
		return 0;
	}

	private static String[] optionLabels(List<Option> options) {
		String[] labels = new String[options.size()];
		for (int i = 0; i < options.size(); i++) {
			labels[i] = options.get(i).label();
		}
		return labels;
	}

	private static String stringParam(Map<String, Object> params, String key) {
		return stringParam(params, key, "");
	}

	private static String stringParam(Map<String, Object> params, String key, String fallback) {
		Object value = params != null ? params.get(key) : null;
		return value != null ? String.valueOf(value) : fallback;
	}

	private static double numericParam(Map<String, Object> params, String key, double fallback) {
		Object value = params != null ? params.get(key) : null;
		return value instanceof Number ? ((Number) value).doubleValue() : fallback;
	}

	private static String valueOf(ImString text) {
		String value = text != null ? text.get() : null;
		return value != null ? value : "";
	}
}
