package com.beatblock.automap.engine;

import com.beatblock.audio.analysis.AudioFeatureTimeline;
import com.beatblock.audio.analysis.DetectedBeat;
import com.beatblock.audio.analysis.EnergyFrame;
import com.beatblock.audio.analysis.FrequencyBands;
import com.beatblock.timeline.Timeline;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.List;

/**
 * Smart Auto-Map Engine 门面：音乐 → 自动生成完整 Timeline（方块动画、摄像机、粒子、节奏结构）。
 * 流程：AudioFeatureTimeline → 音乐结构 → 节奏分类 → 模式过滤 → 动画映射 → 镜头/粒子 → 写入 Timeline。
 */
public final class SmartAutoMapEngine {

	private static final Logger LOGGER = LoggerFactory.getLogger(SmartAutoMapEngine.class);

	/**
	 * 根据音频特征与设置生成完整编排并写入 Timeline。
	 *
	 * @param featureTimeline 来自 Audio Analysis Engine 的分析结果（可为 null，则仅清空不生成）
	 * @param settings        风格、复杂度、镜头/粒子开关
	 * @param timeline        目标时间线
	 * @return 生成统计
	 */
	public static AutoMapResult generate(AudioFeatureTimeline featureTimeline, AutoMapSettings settings, Timeline timeline) {
		AutoMapResult result = new AutoMapResult(0, 0, 0, 0);
		if (timeline == null) return result;
		TimelineBuilder.clearAutoGenerated(timeline);
		if (featureTimeline == null || settings == null) {
			LOGGER.info("BeatBlock Smart Auto-Map: 无音频分析结果或设置，已清空自动轨道");
			return result;
		}
		double duration = featureTimeline.getDurationSeconds();
		float bpm = featureTimeline.getBpm();
		List<FrequencyBands> bands = featureTimeline.getBands();
		List<DetectedBeat> beats = featureTimeline.getBeats();
		List<EnergyFrame> energyFrames = featureTimeline.getEnergyFrames();

		// 1. 音乐结构
		List<MusicSection> sections = MusicStructureAnalyzer.analyze(energyFrames, duration);
		// 2. 节奏分类
		List<RhythmEvent> rhythmEvents = RhythmClassifier.classify(beats, bands);
		// 3. 按复杂度过滤
		rhythmEvents = PatternGenerator.filter(rhythmEvents, settings.getComplexity());
		// 4. 镜头
		List<CameraEvent> cameraEvents = CameraDirector.generate(sections, bpm, duration, settings.getStyle(), settings.isCameraEnabled());
		// 5. 粒子
		List<ParticleEvent> particleEvents = ParticleDirector.generate(bands, settings.isParticlesEnabled());

		int animCount = TimelineBuilder.writeAnimationEvents(timeline, rhythmEvents, settings.getStyle(), settings.getTargetObjectIds());
		int cameraCount = TimelineBuilder.writeCameraEvents(timeline, cameraEvents);
		int particleCount = TimelineBuilder.writeParticleEvents(timeline, particleEvents);

		result = new AutoMapResult(animCount, cameraCount, particleCount, sections.size());
		LOGGER.info("BeatBlock Smart Auto-Map: 动画 {} 个, 镜头 {} 个, 粒子 {} 个, 段落 {} 个",
			animCount, cameraCount, particleCount, sections.size());
		return result;
	}

	/** 生成结果统计 */
	public static final class AutoMapResult {
		private final int animationEvents;
		private final int cameraEvents;
		private final int particleEvents;
		private final int sections;

		public AutoMapResult(int animationEvents, int cameraEvents, int particleEvents, int sections) {
			this.animationEvents = animationEvents;
			this.cameraEvents = cameraEvents;
			this.particleEvents = particleEvents;
			this.sections = sections;
		}

		public int getAnimationEvents() { return animationEvents; }
		public int getCameraEvents() { return cameraEvents; }
		public int getParticleEvents() { return particleEvents; }
		public int getSections() { return sections; }
	}
}
