package com.beatblock.automap.engine;

import com.beatblock.BeatBlock;
import com.beatblock.timeline.CameraKeyframe;
import com.beatblock.timeline.GlobalEvent;
import com.beatblock.timeline.GlobalEventType;
import com.beatblock.timeline.Timeline;
import com.beatblock.timeline.TimelineAnimationEvent;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * 将自动编排结果写入 Timeline：动画事件、摄像机关键帧、全局事件（粒子/灯光）。
 */
public final class TimelineBuilder {

	private static final String DEFAULT_TARGET_ID = "default";

	/**
	 * 清空自动动画、摄像机、全局事件轨道（为重新生成做准备）。
	 */
	public static void clearAutoGenerated(Timeline timeline) {
		if (timeline == null) return;
		timeline.clearAutoAnimationEvents();
		timeline.clearCameraKeyframes();
		timeline.clearGlobalEvents();
	}

	/**
	 * 写入动画事件到自动动画轨道。
	 */
	public static int writeAnimationEvents(Timeline timeline, List<RhythmEvent> rhythmEvents,
	                                       AutoMapStyle style, List<String> targetObjectIds) {
		if (timeline == null || rhythmEvents == null) return 0;
		String targetId = resolveTargetId(targetObjectIds);
		int count = 0;
		for (RhythmEvent e : rhythmEvents) {
			String animId = AnimationMapper.getAnimationTypeId(e, style);
			double dur = AnimationMapper.getDurationSeconds(e.getType(), style);
			Map<String, Object> params = new HashMap<>();
			params.put("energy", e.getEnergy());
			TimelineAnimationEvent ev = new TimelineAnimationEvent(
				"",
				e.getTimeSeconds(),
				dur,
				animId,
				targetId,
				e.getEnergy(),
				params
			);
			timeline.addAutoAnimationEvent(ev);
			count++;
		}
		return count;
	}

	/**
	 * 写入镜头关键帧（仅时间点；动作类型可后续由摄像机系统解析 metadata）。
	 */
	public static int writeCameraEvents(Timeline timeline, List<CameraEvent> cameraEvents) {
		if (timeline == null || cameraEvents == null) return 0;
		int count = 0;
		for (CameraEvent e : cameraEvents) {
			timeline.addCameraKeyframe(new CameraKeyframe(e.getTimeSeconds()));
			count++;
		}
		return count;
	}

	/**
	 * 写入粒子/灯光为全局事件（name 标识类型，如 particle_spark）。
	 */
	public static int writeParticleEvents(Timeline timeline, List<ParticleEvent> particleEvents) {
		if (timeline == null || particleEvents == null) return 0;
		int count = 0;
		for (ParticleEvent e : particleEvents) {
			String name = "particle_" + e.getType().name().toLowerCase();
			timeline.addGlobalEvent(new GlobalEvent(e.getTimeSeconds(), GlobalEventType.SPECIAL, name));
			count++;
		}
		return count;
	}

	private static String resolveTargetId(List<String> targetObjectIds) {
		if (targetObjectIds != null && !targetObjectIds.isEmpty()) return targetObjectIds.get(0);
		if (BeatBlock.blockAnimationEngine != null) {
			var sys = BeatBlock.blockAnimationEngine.getStageObjectSystem();
			var all = sys != null ? sys.getAll() : null;
			if (all != null && !all.isEmpty()) return all.iterator().next().getId();
		}
		return DEFAULT_TARGET_ID;
	}
}
